# Generated by Django 5.1.15 on 2025-12-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_transactionaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionaudit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionaudit',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
