# Generated by Django 5.1.15 on 2025-12-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_transactionaudit_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterparty_name', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=20)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cari Log',
                'verbose_name_plural': 'Cari Logları',
                'ordering': ['-created_at'],
            },
        ),
    ]
