# Generated by Django 5.1.15 on 2025-12-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.CharField(choices=[('CASH', 'Nakit'), ('BANK', 'Banka')], max_length=5),
        ),
    ]
