# Generated by Django 5.1.15 on 2025-12-22 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_transaction_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_direction', models.CharField(max_length=3)),
                ('new_direction', models.CharField(max_length=3)),
                ('old_account', models.CharField(max_length=5)),
                ('new_account', models.CharField(max_length=5)),
                ('old_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_description', models.CharField(blank=True, max_length=255)),
                ('new_description', models.CharField(blank=True, max_length=255)),
                ('old_counterparty', models.CharField(blank=True, max_length=120)),
                ('new_counterparty', models.CharField(blank=True, max_length=120)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='ledger.transaction')),
            ],
            options={
                'verbose_name': 'Hareket Log',
                'verbose_name_plural': 'Hareket Logları',
                'ordering': ['-changed_at'],
            },
        ),
    ]
