# Generated by Django 5.1.15 on 2025-12-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_transactionaudit_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionaudit',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
