# Generated by Django 5.1.15 on 2025-12-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_cashcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='direction',
            field=models.CharField(choices=[('IN', 'Gelir'), ('OUT', 'Gider')], max_length=3),
        ),
    ]
